// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: umsg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_umsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_umsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_umsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_umsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_umsg_2eproto;
namespace umsg {
class sample;
class sampleDefaultTypeInternal;
extern sampleDefaultTypeInternal _sample_default_instance_;
}  // namespace umsg
PROTOBUF_NAMESPACE_OPEN
template<> ::umsg::sample* Arena::CreateMaybeMessage<::umsg::sample>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace umsg {

// ===================================================================

class sample PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:umsg.sample) */ {
 public:
  inline sample() : sample(nullptr) {};
  virtual ~sample();

  sample(const sample& from);
  sample(sample&& from) noexcept
    : sample() {
    *this = ::std::move(from);
  }

  inline sample& operator=(const sample& from) {
    CopyFrom(from);
    return *this;
  }
  inline sample& operator=(sample&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const sample& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const sample* internal_default_instance() {
    return reinterpret_cast<const sample*>(
               &_sample_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(sample& a, sample& b) {
    a.Swap(&b);
  }
  inline void Swap(sample* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(sample* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline sample* New() const final {
    return CreateMaybeMessage<sample>(nullptr);
  }

  sample* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<sample>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const sample& from);
  void MergeFrom(const sample& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(sample* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "umsg.sample";
  }
  protected:
  explicit sample(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_umsg_2eproto);
    return ::descriptor_table_umsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 3,
    kClientsFieldNumber = 1,
    kReaderCntFieldNumber = 2,
  };
  // string _msg = 3;
  void clear__msg();
  const std::string& _msg() const;
  void set__msg(const std::string& value);
  void set__msg(std::string&& value);
  void set__msg(const char* value);
  void set__msg(const char* value, size_t size);
  std::string* mutable__msg();
  std::string* release__msg();
  void set_allocated__msg(std::string* _msg);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release__msg();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated__msg(
      std::string* _msg);
  private:
  const std::string& _internal__msg() const;
  void _internal_set__msg(const std::string& value);
  std::string* _internal_mutable__msg();
  public:

  // uint32 _clients = 1;
  void clear__clients();
  ::PROTOBUF_NAMESPACE_ID::uint32 _clients() const;
  void set__clients(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal__clients() const;
  void _internal_set__clients(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 _reader_cnt = 2;
  void clear__reader_cnt();
  ::PROTOBUF_NAMESPACE_ID::uint32 _reader_cnt() const;
  void set__reader_cnt(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal__reader_cnt() const;
  void _internal_set__reader_cnt(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:umsg.sample)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr _msg_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _clients_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _reader_cnt_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_umsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// sample

// uint32 _clients = 1;
inline void sample::clear__clients() {
  _clients_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 sample::_internal__clients() const {
  return _clients_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 sample::_clients() const {
  // @@protoc_insertion_point(field_get:umsg.sample._clients)
  return _internal__clients();
}
inline void sample::_internal_set__clients(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  _clients_ = value;
}
inline void sample::set__clients(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set__clients(value);
  // @@protoc_insertion_point(field_set:umsg.sample._clients)
}

// uint32 _reader_cnt = 2;
inline void sample::clear__reader_cnt() {
  _reader_cnt_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 sample::_internal__reader_cnt() const {
  return _reader_cnt_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 sample::_reader_cnt() const {
  // @@protoc_insertion_point(field_get:umsg.sample._reader_cnt)
  return _internal__reader_cnt();
}
inline void sample::_internal_set__reader_cnt(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  _reader_cnt_ = value;
}
inline void sample::set__reader_cnt(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set__reader_cnt(value);
  // @@protoc_insertion_point(field_set:umsg.sample._reader_cnt)
}

// string _msg = 3;
inline void sample::clear__msg() {
  _msg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& sample::_msg() const {
  // @@protoc_insertion_point(field_get:umsg.sample._msg)
  return _internal__msg();
}
inline void sample::set__msg(const std::string& value) {
  _internal_set__msg(value);
  // @@protoc_insertion_point(field_set:umsg.sample._msg)
}
inline std::string* sample::mutable__msg() {
  // @@protoc_insertion_point(field_mutable:umsg.sample._msg)
  return _internal_mutable__msg();
}
inline const std::string& sample::_internal__msg() const {
  return _msg_.Get();
}
inline void sample::_internal_set__msg(const std::string& value) {
  
  _msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void sample::set__msg(std::string&& value) {
  
  _msg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:umsg.sample._msg)
}
inline void sample::set__msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  _msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:umsg.sample._msg)
}
inline void sample::set__msg(const char* value,
    size_t size) {
  
  _msg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:umsg.sample._msg)
}
inline std::string* sample::_internal_mutable__msg() {
  
  return _msg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* sample::release__msg() {
  // @@protoc_insertion_point(field_release:umsg.sample._msg)
  return _msg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void sample::set_allocated__msg(std::string* _msg) {
  if (_msg != nullptr) {
    
  } else {
    
  }
  _msg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), _msg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:umsg.sample._msg)
}
inline std::string* sample::unsafe_arena_release__msg() {
  // @@protoc_insertion_point(field_unsafe_arena_release:umsg.sample._msg)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return _msg_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void sample::unsafe_arena_set_allocated__msg(
    std::string* _msg) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (_msg != nullptr) {
    
  } else {
    
  }
  _msg_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      _msg, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:umsg.sample._msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace umsg

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_umsg_2eproto
